import type { Source } from "./types"
import { DEFAULT_SOURCE_SCORE_BY_CATEGORY } from "./types"

/**
 * 初期SOURCE registry。2026-08-11に全件curlでrobots.txt/RSS/Sitemapの実在確認を行った上で登録している
 * (架空URLを断定的に登録しないため。確認ログの要点をnotesに残す)。
 *
 * enabled:true にしているのは「ドメインが実在し、robots.txtが汎用UA(*)を明示的にブロックしておらず、
 * RSSまたはSitemapが実際に200で返ってきた」ものだけ。それ以外は全てenabled:falseで登録し、
 * monitoringMethod:"manual" にしてある(=巡回は行わず、必要なら管理画面からURLを手動追加できる)。
 *
 * URLが確認できなかったものは url を省略している。lib/source-watch/storage.ts の updateSource は
 * url が無いソースを自動的に enabled:false へ強制するため、誤って有効化される事故を防いでいる。
 */

const now = () => new Date().toISOString()

function src(input: Omit<Source, "sourceScore" | "createdAt" | "updatedAt"> & { sourceScore?: number }): Source {
  return {
    ...input,
    sourceScore: input.sourceScore ?? DEFAULT_SOURCE_SCORE_BY_CATEGORY[input.category],
    createdAt: now(),
    updatedAt: now(),
  }
}

export const INITIAL_SOURCES: Source[] = [
  // ================= OFFICIAL =================
  src({
    id: "official-nike-newsroom",
    name: "Nike Newsroom",
    url: "https://about.nike.com/en/newsroom",
    category: "official",
    monitoringMethod: "html",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): about.nike.com/en/newsroom は200。RSS/Sitemapは未確認のためhtml方式(汎用リンク抽出+差分検知)。",
  }),
  src({
    id: "official-adidas-news",
    name: "adidas NEWS",
    url: "https://news.adidas.com",
    feedUrl: "https://news.adidas.com/sitemap/sitemap.xml",
    category: "official",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 60,
    enabled: false,
    imagePolicy: "unknown",
    notes: "robots.txtにSitemap記載あり(確認済み)だが実URLへのfetchは202/403でブロックされる(bot対策の可能性)。要調査、現状は無効化。",
  }),
  src({
    id: "official-newbalance-jp-press",
    name: "New Balance Japan Press",
    url: "https://shop.newbalance.jp",
    category: "official",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 60,
    enabled: false,
    imagePolicy: "unknown",
    notes: "shop.newbalance.jpは既存コードでも使用実績のある確認済みドメインだが、プレスリリース専用ページのURLは未確認。要人力確認。",
  }),
  src({
    id: "official-newbalance-pressbox",
    name: "New Balance Press Box",
    url: "https://newbalance.newsmarket.com/",
    feedUrl: "https://newbalance.newsmarket.com/sitemap/sitemap.xml",
    category: "official",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "WebSearchで特定・確認済み(2026-08-11): newbalance.newsmarket.comが公式Press Box。robots.txt自身が開示するsitemap(/sitemap/sitemap.xmlのサブパス、直下の/sitemap.xmlではない点に注意)は200。",
  }),
  src({
    id: "official-asics-press",
    name: "ASICS Press",
    url: "https://corp.asics.com/jp",
    feedUrl: "https://corp.asics.com/sitemap.xml",
    category: "official",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "press.asics.comはDNS到達不可。corp.asics.com/jp(ASICS公式コーポレートサイト内ニュース)で代替登録。sitemap.xmlは200で実在確認済み。press専用ページではない点に注意。",
  }),
  src({
    id: "official-puma-press",
    name: "PUMA Press / Launch",
    url: "https://about.puma.com/en/",
    feedUrl: "https://about.puma.com/en/sitemap.xml",
    category: "official",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): sitemap 200。",
  }),
  src({
    id: "official-auralee",
    name: "AURALEE Information",
    url: "https://auralee.jp/",
    category: "official",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 60,
    enabled: false,
    imagePolicy: "press_assets_available",
    brands: ["AURALEE"],
    notes: "既存lib/sources.tsのDIRECT_BRAND_SOURCESで使用実績のある確認済みドメイン。専用ニュースフィードは未確認のためmanual。",
  }),
  src({
    id: "official-graphpaper",
    name: "Graphpaper News",
    url: "https://graphpaper-store.com/",
    category: "official",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 60,
    enabled: false,
    imagePolicy: "press_assets_available",
    brands: ["Graphpaper"],
    notes: "既存コードで使用実績のある確認済みドメイン。専用ニュースフィードは未確認のためmanual。",
  }),
  src({
    id: "official-goldwin",
    name: "Goldwin News",
    url: "https://www.goldwin.co.jp/",
    feedUrl: "https://www.goldwin.co.jp/sitemap.xml",
    category: "official",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): sitemap 200。",
  }),

  // ================= PRESS =================
  src({
    id: "press-prtimes",
    name: "PR TIMES",
    url: "https://prtimes.jp",
    feedUrl: "https://prtimes.jp/index.rdf",
    category: "press",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 60,
    enabled: true,
    imagePolicy: "unknown",
    notes: "既存lib/sources.tsで運用実績あり。全ジャンル配信のためキーワードフィルタ必須(lib/source-watch/fetchers/rss.ts参照)。",
  }),

  // ================= RETAILER =================
  src({
    id: "retailer-nike-snkrs",
    name: "Nike SNKRS",
    category: "retailer",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "アプリ中心で公開RSS/Sitemapなし。URL未確定のため手動登録運用。",
  }),
  src({
    id: "retailer-atmos",
    name: "atmos",
    url: "https://www.atmos-tokyo.com/",
    category: "retailer",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "ドメイン実在確認済みだがrobots.txt/sitemap.xmlともに403(bot対策)。自動fetch不可のため手動運用。",
  }),
  src({
    id: "retailer-mita-sneakers",
    name: "mita sneakers",
    url: "https://www.mita-sneakers.co.jp/",
    feedUrl: "https://www.mita-sneakers.co.jp/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): robots.txt/sitemap.xmlともに200、汎用UAブロックなし。",
  }),
  src({
    id: "retailer-billys",
    name: "BILLY'S",
    url: "https://www.billys-tokyo.net/",
    feedUrl: "https://www.billys-tokyo.net/Sitemap_index.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11)。Sitemap URLは大文字始まり(Sitemap_index.xml)である点に注意。",
  }),
  src({
    id: "retailer-union-tokyo",
    name: "UNION TOKYO",
    url: "https://www.uniontokyo.jp/",
    feedUrl: "https://www.uniontokyo.jp/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "WebSearchで特定(2026-08-11、直接推測した.com系ドメインは誤りで正しくは.jp)。robots.txt/sitemap.xmlともに200、汎用UAブロックなし。",
  }),
  src({
    id: "retailer-nubian",
    name: "NUBIAN",
    url: "https://nubiantokyo.com/",
    feedUrl: "https://nubiantokyo.com/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): Shopify標準robots.txt、汎用UAはcart/checkout等のみDisallow。",
  }),
  src({
    id: "retailer-gr8",
    name: "GR8",
    url: "https://gr8.jp/",
    category: "retailer",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "WebSearchでURL特定(2026-08-11、gr8.jp)。robots.txtは404(制限なし)だがsitemap.xml/トップページとも403(bot対策)で自動取得不可のためmanualのまま。",
  }),
  src({
    id: "retailer-beams",
    name: "BEAMS",
    url: "https://www.beams.co.jp/",
    category: "retailer",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "既存lib/sources.tsで使用実績のある確認済みドメインだが、今回の検証環境からは接続できずrobots.txt未確認。有効化前に再確認を推奨。",
  }),
  src({
    id: "retailer-united-arrows",
    name: "UNITED ARROWS",
    url: "https://store.united-arrows.co.jp/",
    category: "retailer",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "ドメイン実在確認済みだがrobots.txtが403(bot対策)。自動fetch不可のため手動運用。",
  }),
  src({
    id: "retailer-coverchord",
    name: "COVERCHORD",
    url: "https://coverchord.com/",
    feedUrl: "https://coverchord.com/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): robots.txt/sitemap.xmlともに200。",
  }),
  src({
    id: "retailer-amanojak",
    name: "Amanojak.",
    url: "https://www.amanojak.jp/",
    feedUrl: "https://www.amanojak.jp/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11)。",
  }),
  src({
    id: "retailer-dsm-ginza",
    name: "Dover Street Market Ginza",
    url: "https://ginza.doverstreetmarket.com/",
    feedUrl: "https://ginza.doverstreetmarket.com/sitemap.xml",
    category: "retailer",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): Shopify標準robots.txt、sitemap 200。",
  }),

  // ================= EARLY MEDIA =================
  src({
    id: "early-sole-retriever",
    name: "Sole Retriever",
    url: "https://www.soleretriever.com/",
    feedUrl: "https://www.soleretriever.com/rss.xml",
    category: "early_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): robots.txt 200(汎用UAブロックなし)、/rss.xml 200。トップページ自体はCloudflare保護で403だがRSSは直接取得可。",
  }),
  src({
    id: "early-sneaker-files",
    name: "Sneaker Files",
    url: "https://sneakerfiles.com/",
    feedUrl: "https://sneakerfiles.com/sitemap_index.xml",
    category: "early_media",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): robots.txtが自らSitemap URLを開示、汎用UAブロックなし。",
  }),
  src({
    id: "early-sneaker-news",
    name: "Sneaker News",
    url: "https://sneakernews.com/",
    category: "early_media",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "⚠判断保留: robots.txtの`User-agent: *`は`Allow: /`だが、Content-Signalで`ai-train=no`を明示し、個別に`ClaudeBot`もDisallowしている。SOURCE WATCHの巡回は独自UA(参照目的、AI学習目的ではない)で*グループが適用されるため技術的には許可範囲内だが、AI関連クローラーを名指しで拒否する意思表示があるため自動有効化は見送り、人間の判断に委ねる。",
  }),
  src({
    id: "early-sneakermarket-ro",
    name: "SneakerMarketRO",
    url: "https://sneakermarket.ro/",
    feedUrl: "https://sneakermarket.ro/sitemap.xml",
    category: "early_media",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 45,
    enabled: true,
    imagePolicy: "unknown",
    notes: "WebSearchで特定・確認済み(2026-08-11): ルーマニアのスニーカーリークコミュニティメディア。robots.txt/sitemap.xmlともに200、汎用UAブロックなし。",
  }),
  src({
    id: "early-sole-supplier",
    name: "The Sole Supplier",
    url: "https://thesolesupplier.co.uk/",
    category: "early_media",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "robots.txt自体は200で読めるが、実ページ/sitemapはCloudflareのチャレンジ応答(202)でブロックされ自動取得不可。",
  }),
  src({
    id: "early-drop-date",
    name: "The Drop Date",
    url: "https://thedropdate.com/",
    category: "early_media",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 45,
    enabled: false,
    imagePolicy: "unknown",
    notes: "ドメイン実在確認済み(robots.txt 200)。RSS/Sitemapは未確認のため、確認でき次第有効化を検討。",
  }),

  // ================= DOMESTIC MEDIA =================
  src({
    id: "domestic-uptodate",
    name: "UP TO DATE",
    url: "https://uptodate.tokyo",
    feedUrl: "https://uptodate.tokyo/feed/",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "affiliate_assets",
    notes: "既存lib/sources.tsから移行(運用実績あり)。掲載画像はブランド提供画像の転載と確認済み(既存コードのコメント参照)。",
  }),
  src({
    id: "domestic-fullress",
    name: "Fullress",
    url: "https://www.fullress.com",
    feedUrl: "https://www.fullress.com/feed/",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "affiliate_assets",
    notes: "既存lib/sources.tsから移行。",
  }),
  src({
    id: "domestic-hypebeast-jp",
    name: "HYPEBEAST Japan",
    url: "https://hypebeast.com/jp",
    feedUrl: "https://hypebeast.com/jp/feed",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "affiliate_assets",
    notes: "既存lib/sources.tsから移行。画像に配信元ブランド名が明記されていることを確認済み。",
  }),
  src({
    id: "domestic-fashionsnap",
    name: "FASHIONSNAP",
    url: "https://www.fashionsnap.com",
    feedUrl: "https://www.fashionsnap.com/rss.xml",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "affiliate_assets",
    notes: "既存lib/sources.tsから移行。画像に\"Image by: [ブランド名]\"表記を確認済み。",
  }),
  src({
    id: "domestic-fashion-press",
    name: "Fashion Press",
    url: "https://www.fashion-press.net",
    feedUrl: "https://www.fashion-press.net/sitemaps/index.xml",
    category: "domestic_media",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "unknown",
    notes: "確認済み(2026-08-11): 汎用UAはAllow: /。画像方針は個別記事ごとに要確認のためunknown(review_required)。",
  }),
  src({
    id: "domestic-houyhnhnm",
    name: "HOUYHNHNM",
    url: "https://www.houyhnhnm.jp/",
    feedUrl: "https://www.houyhnhnm.jp/feed",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "do_not_use",
    notes: "確認済み(2026-08-11): /feed 200。既存lib/sources.tsのコメントで「自社撮影の編集記事が中心」と明記されているためimagePolicyはdo_not_use(テキストでの新着検知のみ利用、画像は使わない)。",
  }),
  src({
    id: "domestic-eyescream",
    name: "EYESCREAM",
    url: "https://eyescream.jp",
    feedUrl: "https://eyescream.jp/feed/",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "do_not_use",
    notes: "確認済み(2026-08-11): /feed/ 200。既存コメントで「Photography_◯◯」クレジット入りの自社発注撮影と明記されているためimagePolicyはdo_not_use。",
  }),
  src({
    id: "domestic-qui",
    name: "QUI",
    url: "https://qui.tokyo/",
    feedUrl: "https://qui.tokyo/feed/",
    category: "domestic_media",
    monitoringMethod: "rss",
    monitoringIntervalMinutes: 180,
    enabled: true,
    imagePolicy: "unknown",
    notes: "WebSearchで特定・確認済み(2026-08-11): 気鋭デザイナーを扱うファッション&カルチャーメディア。/feed/は実際にRSS 2.0を返す(200)。",
  }),

  // ================= RESALE =================
  src({
    id: "resale-ragtag",
    name: "RAGTAG",
    url: "https://www.ragtag.jp/",
    category: "resale",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 600,
    enabled: false,
    imagePolicy: "do_not_use",
    notes: "WebSearchでURL特定(2026-08-11、複数の信頼できる情報源で確認済みの実在ブランド古着チェーン)だが、検証環境からは接続できずrobots.txt/sitemap未確認(前回のBEAMSと同じ現象)。有効化前に別環境での再確認を推奨。今回の優先実装対象外。",
  }),
  src({
    id: "resale-kindal",
    name: "Kindal",
    url: "https://www.kind.co.jp/",
    feedUrl: "https://www.kind.co.jp/sitemap.xml",
    category: "resale",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 600,
    enabled: true,
    imagePolicy: "do_not_use",
    notes: "WebSearchで特定・確認済み(2026-08-11): サイト表記は「kindal」だがドメインはkind.co.jp。robots.txt/sitemap.xmlともに200。画像は二次流通の現物撮影のためdo_not_useのまま(監視のみ)。",
  }),
  src({
    id: "resale-grailed",
    name: "Grailed",
    url: "https://www.grailed.com/",
    feedUrl: "https://sitemap.grailed.com/sitemap.xml.gz",
    category: "resale",
    monitoringMethod: "sitemap",
    monitoringIntervalMinutes: 600,
    enabled: true,
    imagePolicy: "do_not_use",
    notes: "確認済み(2026-08-11): robots.txt(汎用UAブロックなし)・gzip圧縮sitemapとも200、fetcherがgzipに対応済み。画像は出品者個人の現物撮影のためdo_not_use(監視のみ)。",
  }),
  src({
    id: "resale-stockx",
    name: "StockX",
    url: "https://stockx.com/",
    category: "resale",
    monitoringMethod: "manual",
    monitoringIntervalMinutes: 600,
    enabled: false,
    imagePolicy: "do_not_use",
    notes: "ドメイン確認済み、Sitemap開示あり(多言語)だが直接fetchは403(bot対策)。今回の優先実装対象外。",
  }),
]
